Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,12 +21,16 @@ jobs:
       with:
         java-version: '17'
         distribution: 'adopt'
-    
-    - name: Lint code
-      run: mvn checkstyle:check
-      
+        
     - name: Build with Maven
       run: mvn clean install
+
+    - name: Verify JAR file exists
+      run: |
+        if [ ! -f target/demo-0.0.1-SNAPSHOT.jar ]; then
+          echo "JAR file not found!"
+          exit 1
+        fi
 
     - name: Build Docker image
       run: docker build . -t hernangrillo/my-app:${{ github.sha }}
